// Mocks generated by Mockito 5.3.2 from annotations
// in hotel_management_system/test/booking_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i9;

import 'package:hotel_management_system/entity/booking_transaction.dart' as _i7;
import 'package:hotel_management_system/entity/guest.dart' as _i4;
import 'package:hotel_management_system/entity/key_card.dart' as _i5;
import 'package:hotel_management_system/entity/room.dart' as _i6;
import 'package:hotel_management_system/repository/booking_data_repository.dart'
    as _i8;
import 'package:hotel_management_system/service/local_data_service.dart' as _i2;
import 'package:isar/isar.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLocalDataService_0 extends _i1.SmartFake
    implements _i2.LocalDataService {
  _FakeLocalDataService_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeIsarCollection_1<OBJ> extends _i1.SmartFake
    implements _i3.IsarCollection<OBJ> {
  _FakeIsarCollection_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeGuest_2 extends _i1.SmartFake implements _i4.Guest {
  _FakeGuest_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeKeyCard_3 extends _i1.SmartFake implements _i5.KeyCard {
  _FakeKeyCard_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeRoom_4 extends _i1.SmartFake implements _i6.Room {
  _FakeRoom_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeBookingTransaction_5 extends _i1.SmartFake
    implements _i7.BookingTransaction {
  _FakeBookingTransaction_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [BookingDataRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockBookingDataRepository extends _i1.Mock
    implements _i8.BookingDataRepository {
  MockBookingDataRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LocalDataService get localDataService => (super.noSuchMethod(
        Invocation.getter(#localDataService),
        returnValue: _FakeLocalDataService_0(
          this,
          Invocation.getter(#localDataService),
        ),
      ) as _i2.LocalDataService);
  @override
  _i3.IsarCollection<_i7.BookingTransaction> get bookingTransactions =>
      (super.noSuchMethod(
        Invocation.getter(#bookingTransactions),
        returnValue: _FakeIsarCollection_1<_i7.BookingTransaction>(
          this,
          Invocation.getter(#bookingTransactions),
        ),
      ) as _i3.IsarCollection<_i7.BookingTransaction>);
  @override
  _i3.IsarCollection<_i4.Guest> get guests => (super.noSuchMethod(
        Invocation.getter(#guests),
        returnValue: _FakeIsarCollection_1<_i4.Guest>(
          this,
          Invocation.getter(#guests),
        ),
      ) as _i3.IsarCollection<_i4.Guest>);
  @override
  _i3.IsarCollection<_i5.KeyCard> get keyCards => (super.noSuchMethod(
        Invocation.getter(#keyCards),
        returnValue: _FakeIsarCollection_1<_i5.KeyCard>(
          this,
          Invocation.getter(#keyCards),
        ),
      ) as _i3.IsarCollection<_i5.KeyCard>);
  @override
  _i3.IsarCollection<_i6.Room> get rooms => (super.noSuchMethod(
        Invocation.getter(#rooms),
        returnValue: _FakeIsarCollection_1<_i6.Room>(
          this,
          Invocation.getter(#rooms),
        ),
      ) as _i3.IsarCollection<_i6.Room>);
  @override
  _i9.Future<void> createRoom(List<_i6.Room>? rooms) => (super.noSuchMethod(
        Invocation.method(
          #createRoom,
          [rooms],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<void> createKeyCard(List<_i5.KeyCard>? keyCards) =>
      (super.noSuchMethod(
        Invocation.method(
          #createKeyCard,
          [keyCards],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
  @override
  _i9.Future<_i4.Guest> createGuest(
    String? name,
    int? age,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createGuest,
          [
            name,
            age,
          ],
        ),
        returnValue: _i9.Future<_i4.Guest>.value(_FakeGuest_2(
          this,
          Invocation.method(
            #createGuest,
            [
              name,
              age,
            ],
          ),
        )),
      ) as _i9.Future<_i4.Guest>);
  @override
  _i9.Future<_i5.KeyCard> createBookingTransaction(
    _i4.Guest? guest,
    _i5.KeyCard? keyCard,
    _i6.Room? room,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBookingTransaction,
          [
            guest,
            keyCard,
            room,
          ],
        ),
        returnValue: _i9.Future<_i5.KeyCard>.value(_FakeKeyCard_3(
          this,
          Invocation.method(
            #createBookingTransaction,
            [
              guest,
              keyCard,
              room,
            ],
          ),
        )),
      ) as _i9.Future<_i5.KeyCard>);
  @override
  _i9.Future<List<_i5.KeyCard>> createBookingTransactions(
    _i4.Guest? guest,
    List<_i6.Room>? rooms,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #createBookingTransactions,
          [
            guest,
            rooms,
          ],
        ),
        returnValue: _i9.Future<List<_i5.KeyCard>>.value(<_i5.KeyCard>[]),
      ) as _i9.Future<List<_i5.KeyCard>>);
  @override
  _i9.Future<bool> isFloorAvailable(String? floor) => (super.noSuchMethod(
        Invocation.method(
          #isFloorAvailable,
          [floor],
        ),
        returnValue: _i9.Future<bool>.value(false),
      ) as _i9.Future<bool>);
  @override
  _i9.Future<_i6.Room> deleteBookingTransaction(
    _i7.BookingTransaction? bookingTransaction,
    _i5.KeyCard? keyCard,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBookingTransaction,
          [
            bookingTransaction,
            keyCard,
          ],
        ),
        returnValue: _i9.Future<_i6.Room>.value(_FakeRoom_4(
          this,
          Invocation.method(
            #deleteBookingTransaction,
            [
              bookingTransaction,
              keyCard,
            ],
          ),
        )),
      ) as _i9.Future<_i6.Room>);
  @override
  _i9.Future<List<_i6.Room>> deleteBookingTransactionByFloor(String? floor) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteBookingTransactionByFloor,
          [floor],
        ),
        returnValue: _i9.Future<List<_i6.Room>>.value(<_i6.Room>[]),
      ) as _i9.Future<List<_i6.Room>>);
  @override
  _i9.Future<_i7.BookingTransaction?> getBookingTransactionByRoomId(
          int? roomId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookingTransactionByRoomId,
          [roomId],
        ),
        returnValue: _i9.Future<_i7.BookingTransaction?>.value(),
      ) as _i9.Future<_i7.BookingTransaction?>);
  @override
  _i9.Future<_i7.BookingTransaction?> getBookingTransactionByRoomName(
          String? roomName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookingTransactionByRoomName,
          [roomName],
        ),
        returnValue: _i9.Future<_i7.BookingTransaction?>.value(),
      ) as _i9.Future<_i7.BookingTransaction?>);
  @override
  _i9.Future<_i7.BookingTransaction> getBookingTransactionByKeyCardName(
          String? keyCardName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getBookingTransactionByKeyCardName,
          [keyCardName],
        ),
        returnValue:
            _i9.Future<_i7.BookingTransaction>.value(_FakeBookingTransaction_5(
          this,
          Invocation.method(
            #getBookingTransactionByKeyCardName,
            [keyCardName],
          ),
        )),
      ) as _i9.Future<_i7.BookingTransaction>);
  @override
  _i9.Future<_i4.Guest?> getGuestByName(String? guestName) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGuestByName,
          [guestName],
        ),
        returnValue: _i9.Future<_i4.Guest?>.value(),
      ) as _i9.Future<_i4.Guest?>);
  @override
  _i9.Future<_i4.Guest> getGuestById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getGuestById,
          [id],
        ),
        returnValue: _i9.Future<_i4.Guest>.value(_FakeGuest_2(
          this,
          Invocation.method(
            #getGuestById,
            [id],
          ),
        )),
      ) as _i9.Future<_i4.Guest>);
  @override
  _i4.Guest getGuestFromBookingTransaction(
          _i7.BookingTransaction? bookingTransaction) =>
      (super.noSuchMethod(
        Invocation.method(
          #getGuestFromBookingTransaction,
          [bookingTransaction],
        ),
        returnValue: _FakeGuest_2(
          this,
          Invocation.method(
            #getGuestFromBookingTransaction,
            [bookingTransaction],
          ),
        ),
      ) as _i4.Guest);
  @override
  _i9.Future<_i6.Room> getRoomByName(String? roomName) => (super.noSuchMethod(
        Invocation.method(
          #getRoomByName,
          [roomName],
        ),
        returnValue: _i9.Future<_i6.Room>.value(_FakeRoom_4(
          this,
          Invocation.method(
            #getRoomByName,
            [roomName],
          ),
        )),
      ) as _i9.Future<_i6.Room>);
  @override
  _i9.Future<_i6.Room> getRoomById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getRoomById,
          [id],
        ),
        returnValue: _i9.Future<_i6.Room>.value(_FakeRoom_4(
          this,
          Invocation.method(
            #getRoomById,
            [id],
          ),
        )),
      ) as _i9.Future<_i6.Room>);
  @override
  _i9.Future<List<_i6.Room>> getRoomByFloor(String? floor) =>
      (super.noSuchMethod(
        Invocation.method(
          #getRoomByFloor,
          [floor],
        ),
        returnValue: _i9.Future<List<_i6.Room>>.value(<_i6.Room>[]),
      ) as _i9.Future<List<_i6.Room>>);
  @override
  _i9.Future<_i5.KeyCard> getKeyCardById(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getKeyCardById,
          [id],
        ),
        returnValue: _i9.Future<_i5.KeyCard>.value(_FakeKeyCard_3(
          this,
          Invocation.method(
            #getKeyCardById,
            [id],
          ),
        )),
      ) as _i9.Future<_i5.KeyCard>);
  @override
  _i9.Future<_i5.KeyCard> getKeyCardByName(String? name) => (super.noSuchMethod(
        Invocation.method(
          #getKeyCardByName,
          [name],
        ),
        returnValue: _i9.Future<_i5.KeyCard>.value(_FakeKeyCard_3(
          this,
          Invocation.method(
            #getKeyCardByName,
            [name],
          ),
        )),
      ) as _i9.Future<_i5.KeyCard>);
  @override
  _i9.Future<_i5.KeyCard> getFirstUnoccupiedKeyCard() => (super.noSuchMethod(
        Invocation.method(
          #getFirstUnoccupiedKeyCard,
          [],
        ),
        returnValue: _i9.Future<_i5.KeyCard>.value(_FakeKeyCard_3(
          this,
          Invocation.method(
            #getFirstUnoccupiedKeyCard,
            [],
          ),
        )),
      ) as _i9.Future<_i5.KeyCard>);
  @override
  _i9.Future<List<_i5.KeyCard>> getNumberOfUnoccupiedKeyCard(int? count) =>
      (super.noSuchMethod(
        Invocation.method(
          #getNumberOfUnoccupiedKeyCard,
          [count],
        ),
        returnValue: _i9.Future<List<_i5.KeyCard>>.value(<_i5.KeyCard>[]),
      ) as _i9.Future<List<_i5.KeyCard>>);
  @override
  _i9.Future<List<_i6.Room>> getAvailableRoom() => (super.noSuchMethod(
        Invocation.method(
          #getAvailableRoom,
          [],
        ),
        returnValue: _i9.Future<List<_i6.Room>>.value(<_i6.Room>[]),
      ) as _i9.Future<List<_i6.Room>>);
  @override
  _i9.Future<List<_i4.Guest>> getAllGuest() => (super.noSuchMethod(
        Invocation.method(
          #getAllGuest,
          [],
        ),
        returnValue: _i9.Future<List<_i4.Guest>>.value(<_i4.Guest>[]),
      ) as _i9.Future<List<_i4.Guest>>);
  @override
  _i9.Future<List<_i4.Guest>> getAllGuestAgeLessThan(int? age) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllGuestAgeLessThan,
          [age],
        ),
        returnValue: _i9.Future<List<_i4.Guest>>.value(<_i4.Guest>[]),
      ) as _i9.Future<List<_i4.Guest>>);
  @override
  _i9.Future<List<_i4.Guest>> getAllGuestAgeGreaterThan(int? age) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllGuestAgeGreaterThan,
          [age],
        ),
        returnValue: _i9.Future<List<_i4.Guest>>.value(<_i4.Guest>[]),
      ) as _i9.Future<List<_i4.Guest>>);
  @override
  _i9.Future<List<_i4.Guest>> getAllGuestAgeEqualTo(int? age) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllGuestAgeEqualTo,
          [age],
        ),
        returnValue: _i9.Future<List<_i4.Guest>>.value(<_i4.Guest>[]),
      ) as _i9.Future<List<_i4.Guest>>);
  @override
  _i9.Future<List<_i4.Guest>> getAllGuestByFloor(String? floor) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAllGuestByFloor,
          [floor],
        ),
        returnValue: _i9.Future<List<_i4.Guest>>.value(<_i4.Guest>[]),
      ) as _i9.Future<List<_i4.Guest>>);
  @override
  _i9.Future<_i4.Guest> getGuestByRoom(String? roomName) => (super.noSuchMethod(
        Invocation.method(
          #getGuestByRoom,
          [roomName],
        ),
        returnValue: _i9.Future<_i4.Guest>.value(_FakeGuest_2(
          this,
          Invocation.method(
            #getGuestByRoom,
            [roomName],
          ),
        )),
      ) as _i9.Future<_i4.Guest>);
  @override
  _i9.Future<void> clearData() => (super.noSuchMethod(
        Invocation.method(
          #clearData,
          [],
        ),
        returnValue: _i9.Future<void>.value(),
        returnValueForMissingStub: _i9.Future<void>.value(),
      ) as _i9.Future<void>);
}
