name: hotel_management_system
description: A sample command-line application.
version: 1.0.0


environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  isar: ^3.0.5
  path: ^1.8.3
  tuple: ^2.0.1

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
  mockito: ^5.3.2
  isar_generator: ^3.0.5
  build_runner: ^2.3.2
